### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by YanShuang17** [MrGF/py-faster-rcnn-windows#19]
After I compiled the lib for windows, I cd to tools folder and run: python  demo.py, error occurs:
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "C:\Users\ys\Desktop\pycaffe\Faster-RCNN\tools\..\lib\fast_rcnn\test.py", line 16, in <module>
    import caffe
  File "C:\Users\ys\Desktop\pycaffe\Faster-RCNN\tools\..\caffe-fast-rcnn\python\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "C:\Users\ys\Desktop\pycaffe\Faster-RCNN\tools\..\caffe-fast-rcnn\python\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

anything else should I compile besides running python setup.py install/python setup_cuda.py install ???

**Comment by HongSeokHwan** [comment]
Did you solve this issue? Same here!
