### ISSUE TITLE
typeerror: object of type "NoneType" has no len()

### ISSUE THREAD

**Issue by milanwen1983** [MrGF/py-faster-rcnn-windows#2]
Hi, I'm working on faster-rcnn right now, after I replace the lib directory with yours, I type "python setup.py build", some errors appeared like this:
D:\py-faster-rcnn-master\lib>python setup_cuda.py build
running build
running build_ext
building 'nms.gpu_nms' extension
Traceback (most recent call last):
  File "setup_cuda.py", line 122, in <module>
    cmdclass={'build_ext': CUDA_build_ext},
  File "G:\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "G:\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "G:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "G:\Anaconda2\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "G:\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "G:\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "G:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\setuptools\command\build_ext.py", line 66, in run
  File "G:\Anaconda2\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "G:\Anaconda2\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup_cuda.py", line 48, in build_extensions
    build_ext.build_extensions(self)
  File "G:\Anaconda2\lib\site-packages\Cython\Distutils\build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "G:\Anaconda2\lib\site-packages\setuptools-23.0.0-py2.7.egg\setuptools\command\build_ext.py", line 178, in build_exten
sion
  File "G:\Anaconda2\lib\distutils\command\build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "G:\Anaconda2\lib\distutils\msvc9compiler.py", line 546, in compile
    extra_postargs)
  File "setup_cuda.py", line 77, in spawn
    os.path.dirname(find_executable("cl.exe", PATH))
  File "G:\Anaconda2\lib\ntpath.py", line 215, in dirname
    return split(p)[0]
  File "G:\Anaconda2\lib\ntpath.py", line 180, in split
    d, p = splitdrive(p)
  File "G:\Anaconda2\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

Have you got any ideas about this?

**Comment by yxliang** [comment]
I've gotten the same problem:(

**Comment by shaomai00** [comment]
how do you solve this problem?

**Comment by MichaelClerx** [comment]
Hi @milanwen1983 What did you do to solve this issue?

**Comment by shaomai00** [comment]
use cuda7.5(must)

**Comment by yuezhilanyi** [comment]
setup_cuda.py, line 33
modify the path to your own cuda home path, if your cuda version is not 7.5 or not installed there

**Comment by kli017** [comment]
@yuezhilanyi Hi I was using cuda8.0, after modify the path I still get the same error.. must the cuda version be 7.5?

**Comment by yuezhilanyi** [comment]
> @yuezhilanyi Hi I was using cuda8.0, after modify the path I still get the same error.. must the cuda version be 7.5?

It's too long for me to confirm it.
but I think cuda 8.x will be ok
