### ISSUE TITLE
python setup.py error

### ISSUE THREAD

**Issue by gimmy4268** [MrGF/py-faster-rcnn-windows#21]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\faster-rcnn\py-faster-rcnn-master\lib\setup.py", line 66, in <module>
    CUDA = locate_cuda()
  File "C:\Users\USER\Desktop\faster-rcnn\py-faster-rcnn-master\lib\setup.py", line 61, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by ds-motivo** [comment]
Same here.

**Comment by AvaniPitre** [comment]
hi you solve this? I have been facing same error

**Comment by King-of-Infinite-Space** [comment]
Python 3 renamed dict.iteritems -> dict.items

from [stackoverflow](https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems-when-trying-to-use-networkx)
