### ISSUE TITLE
error : build the setup_cuda.py cannot find cl.exe in path?

### ISSUE THREAD

**Issue by Sherlock-hh** [MrGF/py-faster-rcnn-windows#32]
hi, I'm trying to build the gpu_nms with:
cuda 10.1
windows 10
python37
vs2019
I just trun ''cm35'' to ''cm 75'',
and change the path of cuda:
'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\include'
Is there anything else need to change?
i'll be very appreciate that any one can help，looking for your reply.
running build_ext
building 'nms.gpu_nms' extension
Traceback (most recent call last):
  File "setup_cuda.py", line 122, in <module>
    cmdclass={'build_ext': CUDA_build_ext},
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\AppData\Local\conda\conda\envs\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\AppData\Local\conda\conda\envslib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup_cuda.py", line 48, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\\AppData\Local\conda\conda\envs\\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\\AppData\Local\conda\conda\envs\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\\AppData\Local\conda\conda\envs\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\\AppData\Local\conda\conda\envs\\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\AppData\Local\conda\conda\envs\\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\\AppData\Local\conda\conda\envs\\lib\distutils\_msvccompiler.py", line 423, in compile
    self.spawn(args)
  File "setup_cuda.py", line 77, in spawn
    os.path.dirname(find_executable("cl.exe", PATH))
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "C:\Users\\AppData\Local\conda\conda\envs\-py37-t1\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by fangzhouAlonso** [comment]
hello,have u sloved this problem?

**Comment by Sherlock-hh** [comment]
> hello,have u sloved this problem?

sorry, i haven‘t

**Comment by frozen30** [comment]
hello,have u sloved this problem?
