### ISSUE TITLE
Compiler setup.py error

### ISSUE THREAD

**Issue by stevewusin** [MrGF/py-faster-rcnn-windows#9]
compiler：python setup.py install （I just need CPU edition，so, I don't need to compiler nvcc and cuda library ???）：
Traceback (most recent call last):
File "setup.py", line 66, in <module>
CUDA = locate_cuda()
File "setup.py", line 52, in locate_cuda
raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add
it to your path, or set $CUDA_PATH
@MrGF

**Comment by haibucuo0** [comment]
hi，did you successed？

**Comment by Yu0525** [comment]
Set the `CUDA_PATH` in Environment Variable.
Please refer to http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#sample-projects

**Comment by x1aoo** [comment]
> Set the `CUDA_PATH` in Environment Variable.
> Please refer to http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#sample-projects

Hi,

How to deal with the computer without NVIDIA GPU, actually I got the intel gpu in my computer and want to use CPU
to do the inference.

@MrGF @seizeTheDayMin

**Comment by krishnaths** [comment]
Similar issue and i have a mac os :(
